---
- name: Deploy to production
  hosts: virtualmachines
  remote_user: crispyrice

  tasks:
  - name: Pull container
    ansible.builtin.shell:
      cmd: "docker pull ghcr.io/cryptichat/client-web:main"
  - name: Re-run out of date containers
    ansible.builtin.shell:
      cmd: "docker-compose up -d"
      chdir: /home/crispyrice/web
