---
- name: Deploy to production
  hosts: virtualmachines
  remote_user: crispyrice

  tasks:
  - name: Pull container
    ansible.builtin.shell:
      cmd: "docker pull '{{ lookup('ansible.builtin.env', 'DOCKER_METADATA_OUTPUT_TAGS') }}'"
  - name: Re-run out of date containers
    ansible.builtin.shell:
      cmd: "docker-compose up -d"
      chdir: /home/crispyrice/web
